import './js/pre-loader-spinner';
import './js/mobile-menu';
import './js/activMenu';
import './js/modal-trailer';
import './js/hero';
import './js/theme-switcher';
import './js/modal-footer';
import './js/galery-library';
import './js/scroll-to-top';